# Generated by Django 4.2.9 on 2024-02-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSphereApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_start', models.CharField(max_length=100)),
                ('academic_end', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
