# Generated by Django 4.2.9 on 2024-02-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSphereApp', '0009_staff_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_notification',
            old_name='staff',
            new_name='staff_id',
        ),
    ]
