# Generated by Django 4.2.9 on 2024-02-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSphereApp', '0020_alter_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
