# Generated by Django 5.0.2 on 2024-04-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSphereApp', '0022_hod_staff_notification_hod_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_notification',
            name='hod_id',
        ),
        migrations.DeleteModel(
            name='HOD',
        ),
    ]
